name: Work Stats Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update stats for readme profile
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          REPOSITORY: zeative/zeative # optional
          SHOW_TITLE: true # optional
          TIME_RANGE: all_time # optional
          LANG_COUNT: 20 # optional
          SHOW_TIME: true # optional
          SHOW_TOTAL: true # optional
          SHOW_EDITORS: true # optional
          SHOW_SHORT_INFO: false # optional
          BLOCKS: ▱▰ # optional
          STOP_AT_OTHER: true # optional
          SHOW_MASKED_TIME: false # optional

